### ISSUE TITLE
Feature Request: Send Mode Via CAT

### ISSUE THREAD

**Issue by DJUnreal** [M0LTE/satpc32-dde-utils#1]
What we have so far is awesome - it picks up and sends the downlink frequency from SatPC32 directly to a CAT port which I drive SDR Console with.

It would be even more awesome if the mode could be sent via CAT as well when it changes (or even periodically). At the moment, on change of satellite, the mode doesn't get sent when the stream starts. Whether you wish you send the mode each time is up to you (not sure the logistics of CAT and whether it's necessary/sensible/too resource intensive), but sending the mode at least once per satellite change would be awesome!

**Comment by M0LTE** [comment]
Roger :)
